name: Run runbooks tests
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@b469512bc31f0425270a12b87ebe68807c3a1daf # v0.0.46
      - run: |
          pip install -r requirements.txt
          AWS_DEFAULT_REGION=eu-west-2 pytest
